Optimized and cleaned up the snap
alexmurray/amberol-snap pull request #8
Opened 2023-04-22 20:37 UTC by soumyaDghosh

2023-04-24 12:04 UTC, alexmurray requested changes
Can you please add some more details on why you have made these changes?

2023-04-24 12:04 UTC, alexmurray commented on snapcraft.yaml
> +#summary: A small and simple sound and music player that is well integrated with GNOME.
Why have you commented out the summary and description?

2023-04-24 12:04 UTC, alexmurray commented on snapcraft.yaml
> +icon: io.bassi.Amberol.svg
I would prefer not to ship a copy of the icon in the snap repo - can you explain why this is needed?

2023-04-24 12:04 UTC, alexmurray commented on snapcraft.yaml
> +      snap/amberol/current/usr: usr
this change seems redundant - can you explain why it is needed?

2023-04-24 12:04 UTC, alexmurray commented on snapcraft.yaml
> +      #- libadwaita-1-0
instead of commenting out parts of the yaml these should just be removed if they are not needed anymore?

2023-04-25 20:04 UTC, soumyaDghosh commented on snapcraft.yaml
> +#summary: A small and simple sound and music player that is well integrated with GNOME.
Those are adopted from appdata, you can completely remove it

2023-04-25 20:05 UTC, soumyaDghosh commented on snapcraft.yaml
> +      snap/amberol/current/usr: usr
Yes. you can skip that too, That's not a big thing

2023-04-25 20:06 UTC, soumyaDghosh commented on snapcraft.yaml
> +icon: io.bassi.Amberol.svg
It's easy to have a icon in the repo and done, it'll auto copy it in the snap store also and within the app, we'll not need to make the changes in the desktop file anymore

2023-04-25 20:06 UTC, soumyaDghosh commented on snapcraft.yaml
> +      #- libadwaita-1-0
Okay, I am changing them

2023-05-07 05:34 UTC, closed without merging